
image:
  file: .gitpod.Dockerfile

tasks:
  - init: (cd mobile && npm install)
    command: cd mobile && EXPO_TOKEN="" npx expo start --dev-client --tunnel -c
  - init: docker-compose pull && docker-compose build
    command: docker-compose up -d 

ports:
  - port: 5010
    visibility: public

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - jpoissonnier.vscode-styled-components
    - styled-components.vscode-styled-components
